### ISSUE TITLE
Glassfish service does not start "timeout was exceeded "

### ISSUE THREAD

**Issue by zalpany2000** [IQSS/dataverse-ansible#203]
Dear Dataverse people :)

I was taking my first shoot to deploy Dataverse pilot instance using the Ansible Pb, 

Environment, 

Centos 7, last update 12.06.2020 11:32
Git Repo clone date: 12.06.2020 14:200
the server has Internet access via Proxy "in case this might cause difference" Proxy is added to the Profile and globally.
error: 

`TASK [dataverse : start glassfish with systemd] *******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service glassfish: Job for glassfish.service failed because a timeout was exceeded. See \"systemctl status glassfish.service\" and \"journalctl -xe\" for details.\n"}
`

 systemctl status glassfish.service:

> `glassfish.service - GlassFish Server 
 Loaded: loaded (/usr/lib/systemd/system/glassfish.service; enabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Sat 2020-06-13 12:12:33 CEST; 14min ago
  Process: 13420 ExecStop=/usr/bin/java -jar /usr/local/glassfish5/glassfish/lib/client/appserver-cli.jar stop-domain (code=exited, status=1/FAILURE)
  Process: 14374 ExecStart=/usr/bin/java -jar /usr/local/glassfish5/glassfish/lib/client/appserver-cli.jar start-domain (code=exited, status=143)
 Main PID: 11016 (code=exited, status=0/SUCCESS)

Jun 13 12:08:03 bibsys03.whu.edu systemd[1]: Starting GlassFish Server...
Jun 13 12:11:03 bibsys03.whu.edu systemd[1]: glassfish.service start operation timed out. Terminating.
Jun 13 12:11:03 bibsys03.whu.edu systemd[1]: glassfish.service: control process exited, code=exited status=143
Jun 13 12:12:33 bibsys03.whu.edu systemd[1]: glassfish.service stop-final-sigterm timed out. Killing.
Jun 13 12:12:33 bibsys03.whu.edu systemd[1]: Failed to start GlassFish Server.
Jun 13 12:12:33 bibsys03.whu.edu systemd[1]: Unit glassfish.service entered failed state.
Jun 13 12:12:33 bibsys03.whu.edu systemd[1]: glassfish.service failed.
`
in the logfile, there are some warning messages :

> [#|2020-06-13T12:08:12.590+0200|WARNING|Payara 5.201|org.glassfish.grizzly.config.GenericGrizzlyListener|_ThreadID=21;_ThreadN$
  Unable to construct HTTP/2 Addon
java.lang.NoClassDefFoundError: org/glassfish/grizzly/npn/AlpnServerNegotiator
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configureHttp2Support(GenericGrizzlyListener.java:806)
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configureHttpProtocol(GenericGrizzlyListener.java:782)
        at com.sun.enterprise.v3.services.impl.GlassfishNetworkListener.configureHttpProtocol(GlassfishNetworkListener.java:21$
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configureSubProtocol(GenericGrizzlyListener.java:456)
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configureProtocol(GenericGrizzlyListener.java:445)
        at org.glassfish.grizzly.config.GenericGrizzlyListener.configure(GenericGrizzlyListener.java:341)
        at com.sun.enterprise.v3.services.impl.GrizzlyProxy.initialize(GrizzlyProxy.java:126)
        at com.sun.enterprise.v3.services.impl.GrizzlyService.createNetworkProxy(GrizzlyService.java:671)
        at com.sun.enterprise.v3.services.impl.GrizzlyService.postConstruct(GrizzlyService.java:593)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.glassfish.grizzly.npn.AlpnServerNegotiator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1179)
        at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1618)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1548)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 23 more`

also : 

> `[#|2020-06-13T12:08:27.352+0200|WARNING|Payara 5.201|javax.enterprise.system.security.ssl|_ThreadID=18;_ThreadName=RunLevelCon$
  The SSL certificate has expired: [
[
  Version: V3
  Subject: CN=AddTrust Class 1 CA Root, OU=AddTrust TTP Network, O=AddTrust AB, C=SE
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5

  Key:  Sun RSA public key, 2048 bits .......
`

any suggestions where should I start ?

thanks

**Comment by donsizemore** [comment]
Hello, did you see this link I sent you in IRC?
https://github.com/payara/Payara/issues/3138

**Comment by zalpany2000** [comment]
@donsizemore I did actually

now me domain.xml have only 

>         <jvm-options>-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>

also, I followed the expired SSL certificates errors, deleted the expired certs. 

the weird issue, I tried later yesterday to deploy the same repo locally on a VirtualBox CentOS 7 and it just worked, regardless the glassfish logs throw the same errors but the glassfish service started normally

**Comment by zalpany2000** [comment]
also starting the domain manually using asadmin works just fine, the problem is with the service specifically

**Comment by zalpany2000** [comment]
sorry for hustle, I should have started there :) 
I changed the service timeout to 10 min, then the service was starting just fine.

**Comment by zalpany2000** [comment]
now, I ran into 2nd error.

> TASK [dataverse : set siteurl] ***************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/glassfish5/bin/asadmin create-jvm-options \"-Ddataverse.siteUrl=http\\\\://bibsys03.whu.edu\"", "delta": "0:00:00.665839", "end": "2020-06-14 13:07:28.539831", "msg": "non-zero return code", "rc": 1, "start": "2020-06-14 13:07:27.873992", "stderr": "remote failure: JVM option -Ddataverse.siteUrl=http://bibsys03.whu.edu already exists in the configuration.", "stderr_lines": ["remote failure: JVM option -Ddataverse.siteUrl=http://bibsys03.whu.edu already exists in the configuration."], "stdout": "Command create-jvm-options failed.", "stdout_lines": ["Command create-jvm-options failed."]}

why it is a fatal error that the JVM option is already exists? also should I try delete it ?
