### ISSUE TITLE
The dataset could not be created: ArrayIndexOutOfBoundsException edu.ucsb.nceas.ezid.EZIDService.getMetadata(EZIDService.java:268)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#29]
Tested on https://github.com/IQSS/dataverse/commit/635b208

I can't create a dataset.

Screenshot:

<img width="1060" alt="screen shot 2018-10-01 at 8 59 21 pm" src="https://user-images.githubusercontent.com/21006/46323568-f3d2c480-c5bc-11e8-9865-c30b1b3b5a62.png">

Stack trace:

Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at edu.ucsb.nceas.ezid.EZIDService.getMetadata(EZIDService.java:268)
        at edu.harvard.iq.dataverse.DOIEZIdServiceBean.alreadyExists(DOIEZIdServiceBean.java:56)

We probably need a fix similar to https://github.com/IQSS/dataverse/pull/5124 to put the EZID username and password back in the config. I was removed in 4.9.3. Longer term we need to figure out what to do when EZID really goes away for real. See https://github.com/IQSS/dataverse/issues/5024#issuecomment-423610278 for the possibility of programmatic access to test DataCite credentials. For now, the documented process for getting these credentials is manual: http://guides.dataverse.org/en/4.9.3/installation/config.html#persistent-identifiers-and-publishing-datasets

<img width="869" alt="screen shot 2018-10-01 at 9 05 36 pm" src="https://user-images.githubusercontent.com/21006/46323734-c76b7800-c5bd-11e8-80ea-e5856e4003e5.png">

**Comment by pdurbin** [comment]
I just hacked on ec2-create-instance.sh in the following way...

```
(aws) murphy:installer pdurbin$ git diff ec2-create-instance.sh
diff --git a/scripts/installer/ec2-create-instance.sh b/scripts/installer/ec2-create-instance.sh
index fe84c11..cd6d175 100755
--- a/scripts/installer/ec2-create-instance.sh
+++ b/scripts/installer/ec2-create-instance.sh
@@ -4,6 +4,9 @@
 
 SUGGESTED_REPO_URL='https://github.com/IQSS/dataverse.git'
 SUGGESTED_BRANCH='develop'
+DATAVERSE_DOI_USERNAME='REDACTED'
+DATAVERSE_DOI_PASSWORD='REDACTED'
+DATAVERSE_DOI_BASEURL='https://mds.test.datacite.org'
 
 usage() {
   echo "Usage: $0 -r $REPO_URL -b $SUGGESTED_BRANCH" 1>&2
@@ -100,8 +103,11 @@ ssh -T -i $PEM_FILE -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/nu
 sudo yum -y install epel-release
 sudo yum -y install git nano ansible
 git clone https://github.com/IQSS/dataverse-ansible.git dataverse
+cd dataverse
+git checkout switch_to_datacite
+cd ..
 export ANSIBLE_ROLES_PATH=.
-ansible-playbook -i dataverse/inventory dataverse/dataverse.pb --connection=local --extra-vars "dataverse_branch=$BRANCH_NAME dataverse_repo=$REPO_URL"
+ansible-playbook -i dataverse/inventory dataverse/dataverse.pb --connection=local --extra-vars "dataverse_branch=$BRANCH_NAME dataverse_repo=$REPO_URL dataverse_doi_baseurl=$DATAVERSE_DOI_BASEURL dataverse_doi_username=$DATAVERSE_DOI_USERNAME dataverse_doi_password=$DATAVERSE_DOI_PASSWORD"
 EOF
 
 # Port 8080 has been added because Ansible puts a redirect in place
(aws) murphy:installer pdurbin$ 

```

And it worked! I can publish now:

![screen shot 2018-10-10 at 9 48 22 am](https://user-images.githubusercontent.com/21006/46740919-e8913000-cc71-11e8-986f-0db1a3e08bde.png)

I'm going to go ahead and merge pull request #30 so I don't need the `git checkout switch_to_datacite` step.

**Comment by pdurbin** [comment]
Now that we have https://github.com/IQSS/dataverse/issues/5162 to represent the work we need to do on the ec2-create-instance.sh script (thanks, @donsizemore !), I'm going to close this issue.
